// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCp0jkHzMsANVMTib7pLtuq2UqfRh-6iTM',
    appId: '1:739581302488:web:77fff3894909afb125a9ad',
    messagingSenderId: '739581302488',
    projectId: 'travelers-c4a62',
    authDomain: 'travelers-c4a62.firebaseapp.com',
    storageBucket: 'travelers-c4a62.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBiqdUIKSNfrdCQQilnw12LFIXu0vo9WIQ',
    appId: '1:739581302488:android:ab788c6c4a9de42725a9ad',
    messagingSenderId: '739581302488',
    projectId: 'travelers-c4a62',
    storageBucket: 'travelers-c4a62.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCqv78XVMGUP_1aGj2ms3q9dWzy53FHTSg',
    appId: '1:739581302488:ios:8c3f6a68947d0d4225a9ad',
    messagingSenderId: '739581302488',
    projectId: 'travelers-c4a62',
    storageBucket: 'travelers-c4a62.appspot.com',
    iosBundleId: 'com.example.travelers',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCqv78XVMGUP_1aGj2ms3q9dWzy53FHTSg',
    appId: '1:739581302488:ios:c3abea5c47e4414b25a9ad',
    messagingSenderId: '739581302488',
    projectId: 'travelers-c4a62',
    storageBucket: 'travelers-c4a62.appspot.com',
    iosBundleId: 'com.example.travelers.RunnerTests',
  );
}
